### ISSUE TITLE
Issue with EPI Judge Java code 

### ISSUE THREAD

**Issue by sandredd** [adnanaziz/EPIJudge#222]
I see below error after all test cases are passed. I have cloned a new copy and tried and i get same results.

Critical error(epi.test_framework.minimal_json.ParseException): Unexpected end of input at 1110:20
epi.test_framework.minimal_json.ParseException: Unexpected end of input at 1110:20
	at epi.test_framework.minimal_json.JsonParser.error(JsonParser.java:478)
	at epi.test_framework.minimal_json.JsonParser.expected(JsonParser.java:472)
	at epi.test_framework.minimal_json.JsonParser.readStringInternal(JsonParser.java:300)
	at epi.test_framework.minimal_json.JsonParser.readName(JsonParser.java:249)
	at epi.test_framework.minimal_json.JsonParser.readObject(JsonParser.java:226)
	at epi.test_framework.minimal_json.JsonParser.readValue(JsonParser.java:165)
	at epi.test_framework.minimal_json.JsonParser.readObject(JsonParser.java:234)
	at epi.test_framework.minimal_json.JsonParser.readValue(JsonParser.java:165)
	at epi.test_framework.minimal_json.JsonParser.readObject(JsonParser.java:234)
	at epi.test_framework.minimal_json.JsonParser.readValue(JsonParser.java:165)
	at epi.test_framework.minimal_json.JsonParser.parse(JsonParser.java:140)
	at epi.test_framework.minimal_json.JsonParser.parse(JsonParser.java:73)
	at epi.test_framework.minimal_json.Json.parse(Json.java:286)
	at epi.test_framework.GenericTest.updateTestPassed(GenericTest.java:181)
	at epi.test_framework.GenericTest.runTests(GenericTest.java:152)
	at epi.test_framework.GenericTest.genericTestMain(GenericTest.java:67)
	at epi.test_framework.GenericTest.runFromAnnotations(GenericTest.java:233)
	at epi.IsStringPalindromicPunctuation.main(IsStringPalindromicPunctuation.java:25)

**Comment by zorro786** [comment]
Facing same in IntelliJ Idea 2021. Looks like the `problem_mapping.json` file is being overwritten or corrupted somehow. Similar issue: https://github.com/adnanaziz/EPIJudge/issues/215
@adnanaziz @tsunghsienlee
